apiVersion: v1
kind: Service
metadata:
  name: gnosisdb-web
  labels:
    app: gnosisdb-web
spec:
  type: "LoadBalancer"
  ports:
    - name: "http"
      protocol: "TCP"
      port: 80
      targetPort: 8000
    # Uncomment this and comment previous block to enable HTTPS (it's the recommended option)
    # - name: "https"
    #   protocol: "TCP"
    #   port: 443
    #   targetPort: 8000
  selector:
    app: gnosisdb-web
