version: '2'

services:
  ipfs:
    hostname: ipfs
    build:
      context: .
      dockerfile: docker/ipfs/Dockerfile
    ports:
      - "4001:4001"
      - "5001:5001"
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=gnosisdb
      - RABBITMQ_DEFAULT_PASS=gnosisdb
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    links:
      - db
      - ipfs
    depends_on:
      - ipfs
      - db
    working_dir: /gnosisdb
    command: scripts/run_web.sh
    ports:
      - "8000:8000"
      - "27017"
      - "5432"
  worker:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: scripts/run_celery_worker.sh
    env_file:
      - .env
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - db
      - rabbit

  scheduler:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: scripts/run_celery_scheduler.sh
    env_file:
      - .env
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - db
      - rabbit
